# Generated by Django 2.0 on 2018-01-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.AddField(
            model_name='work',
            name='work_image_name',
            field=models.CharField(default='default_holder', max_length=100),
            preserve_default=False,
        ),
    ]
