# Generated by Django 2.0 on 2018-01-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_auto_20180105_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_title', models.CharField(max_length=200)),
                ('education_date', models.CharField(max_length=200)),
                ('education_text', models.CharField(max_length=2000)),
                ('education_image_name', models.CharField(max_length=100)),
            ],
        ),
    ]
