# Generated by Django 2.0 on 2018-01-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=200)),
                ('art_year', models.CharField(max_length=20)),
                ('art_text', models.CharField(max_length=1000)),
                ('art_image_name', models.CharField(max_length=100)),
            ],
        ),
    ]
