# Generated by Django 2.0 on 2018-01-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='art_year',
            field=models.IntegerField(),
        ),
    ]
