# Generated by Django 2.0 on 2018-01-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_year', models.IntegerField()),
                ('project_text', models.CharField(max_length=2000)),
                ('project_image_name', models.CharField(max_length=100)),
            ],
        ),
    ]
